pipeline {
    environment {
        BASE_FOLDER = 'helm_analytics_api_deploy'
        DOCKER_FOLDER = 'helm_analytics_api_deploy/docker/analytics-api'
        DOCKER_REGISTRY_URL = ''
        DOCKER_REGISTRY_CREDENTIAL = 'dockerhub_nicosp'
        IMAGE = 'nicosp/analytics-api'
        IMAGE_VERSION = '0.0.1'
    }
  agent any
  stages {
    stage('Build Image') {
      steps {
        sh '''
           cd ${DOCKER_FOLDER}
           ls
           sudo docker version
           '''
      }
    }
    stage('Deploy To Kubernetes') {
      steps {
        sh 'cd ${BASE_FOLDER}'
//         sh ''' cd ${BASEFOLDER}
// helm upgrade --install analytics-api ./analytics-api -n analytics-api
// '''
      }
    }    
  }
}

