pipeline {
    environment {
        BASE_FOLDER = 'helm_analytics_api_deploy'
        DOCKER_FOLDER = 'helm_analytics_api_deploy/docker/analytics-api'
        DOCKER_REGISTRY_URL = ''
        DOCKER_REGISTRY_CREDENTIAL = 'dockerhub_nicosp'
        IMAGE = 'nicosp/analytics-api'
        IMAGE_VERSION = '0.0.1'
    }
  agent any
  stages {
    stage('Build Artifact') {
      agent {
        docker {
          image 'gradle:7.0.2-jdk11'
          reuseNode true
        }
      }
      post {
        always {
          junit '**/build/test-results/test/TEST-*.xml'
        }
      }
      steps {
        sh '''gradle tasks --stacktrace'''
      }
    }
    stage('Build Image') {
      steps {
        sh '''
           cd ${DOCKER_FOLDER}
           docker build -t ${IMAGE}:${IMAGE_VERSION} .
           '''
      }
    }
    stage('Clean Up') {
      steps {
        sh '''docker rmi ${IMAGE}'''
      }
    }
    stage('Deploy To Kubernetes') {
      steps {
        sh 'cd ${BASE_FOLDER}'
//         sh ''' cd ${BASEFOLDER}
// helm upgrade --install analytics-api ./analytics-api -n analytics-api
// '''
      }
    }    
  }
}

