pipeline {
  environment {
    DOCKER_REGISTRY_URL = ''
    DOCKER_REGISTRY_CREDENTIAL = '4c5f327f-ae16-4ffe-8142-6007c7137847'
    IMAGE = 'nicosp/my-apache2'
    FOLDER = 'webserver'
  }
  agent any
  stages {
    stage('Build') {
      steps {
        sh '''cd ${FOLDER}
docker build -t ${IMAGE} .
'''
      }
    }
    stage('Deploy') {
      steps {
        script {
          docker.withRegistry('', DOCKER_REGISTRY_CREDENTIAL) {
            image = docker.image(IMAGE)
            image.push()
          }
        }
      }
    }
    stage('Clean Up') {
      steps {
        sh '''docker rmi ${IMAGE}'''
      }
    }
  }
}

