pipeline {
    environment {
        FOLDER = 'helm_deploy'
    }
  agent any
  stages {
    stage('Kubedeploy') {
      steps {
        sh ''' cd ${FOLDER}
helm upgrade --install example ./mychart -n dev-test
'''
      }
    }    
  }
}

