pipeline {
    environment {
        FOLDER = 'helm_deploy'
    }
  agent any
  stages {
    stage('Kubedeploy') {
      steps {
        sh ''' cd ${FOLDER}
helm install example ./mychart -n dev-test
'''
      }
    }
    
    
  }
}
	